/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildHeartlineRouteImport } from './routes/build/heartline'
import { Route as ResearchCancershiftRouteImport } from './routes/research/cancershift'
import { Route as WriteFloodedRouteImport } from './routes/write/flooded'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildHeartlineRoute = BuildHeartlineRouteImport.update({
  id: '/build/heartline',
  path: '/build/heartline',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchCancershiftRoute = ResearchCancershiftRouteImport.update({
  id: '/research/cancershift',
  path: '/research/cancershift',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteFloodedRoute = WriteFloodedRouteImport.update({
  id: '/write/flooded',
  path: '/write/flooded',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build/heartline': typeof BuildHeartlineRoute
  '/research/cancershift': typeof ResearchCancershiftRoute
  '/write/flooded': typeof WriteFloodedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build/heartline': typeof BuildHeartlineRoute
  '/research/cancershift': typeof ResearchCancershiftRoute
  '/write/flooded': typeof WriteFloodedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build/heartline': typeof BuildHeartlineRoute
  '/research/cancershift': typeof ResearchCancershiftRoute
  '/write/flooded': typeof WriteFloodedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/build/heartline' | '/research/cancershift' | '/write/flooded'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/build/heartline' | '/research/cancershift' | '/write/flooded'
  id:
    | '__root__'
    | '/'
    | '/build/heartline'
    | '/research/cancershift'
    | '/write/flooded'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildHeartlineRoute: typeof BuildHeartlineRoute
  ResearchCancershiftRoute: typeof ResearchCancershiftRoute
  WriteFloodedRoute: typeof WriteFloodedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/heartline': {
      id: '/build/heartline'
      path: '/build/heartline'
      fullPath: '/build/heartline'
      preLoaderRoute: typeof BuildHeartlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/cancershift': {
      id: '/research/cancershift'
      path: '/research/cancershift'
      fullPath: '/research/cancershift'
      preLoaderRoute: typeof ResearchCancershiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/flooded': {
      id: '/write/flooded'
      path: '/write/flooded'
      fullPath: '/write/flooded'
      preLoaderRoute: typeof WriteFloodedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildHeartlineRoute: BuildHeartlineRoute,
  ResearchCancershiftRoute: ResearchCancershiftRoute,
  WriteFloodedRoute: WriteFloodedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
